# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 109283cf0b27fe577c23bc24921cbb467ef9fdfd7e6d8775374fc7a9258488fe98107743061db68ba4f1a7fb85623665a4814ba20c9c7a388ba1cdd4920ad4a6

test:
  secret_key_base: e528ae4e255068c5d5a8543fcb22da70b614dedaa8063ed1ca61b95c74d109bc09174e8381345b1a03f1bb204544c4ed77ba8fc0cfeea5049d392b84ee5b0c06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
